SELECT DISTINCT CITY from STATION WHERE CITY LIKE '%a';
SELECT DISTINCT CITY from STATION WHERE CITY LIKE '%e';
SELECT DISTINCT CITY from STATION WHERE CITY LIKE '%i';
SELECT DISTINCT CITY from STATION WHERE CITY LIKE '%o';
SELECT DISTINCT CITY from STATION WHERE CITY LIKE '%u';