SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%[a,e,i,o,u]';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%[a,e,i,o,u]';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%[a,e,i,o,u]';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%[a,e,i,o,u]';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%[a,e,i,o,u]';